### ISSUE TITLE
Expose password dialog

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#10]
It would be very useful to expose a standard password dialog that lets the user enter text in a password dialog box and then the result is returned to code.

**Comment by jeroenooms** [comment]
Preferably the default behaviour would work as a drop-in replacement of `readline` with its first argument `prompt` to specify a custom question, and have it return the password as a plain-text string.

```r
password <- rstudioapi::readpass(prompt = "Please enter your password")
```

Of course it could take additional arguments to customize this behavior.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudioapi/commit/e2c20ef8c3b810ff43c7bf86562f7f0294098334

**Comment by jeroenooms** [comment]
I'm getting:

```r
> library(rstudioapi)
> askForPassword("foo")
Error: Function askForPassword not found in RStudio
```

**Comment by kevinushey** [comment]
@jeroenooms a similar change needs to be made in the IDE to export the function as an API function, I believe.

**Comment by jeroenooms** [comment]
Yes I'm sorry I just realized that this probably requires https://github.com/rstudio/rstudio/commit/359d0985387ebebc1c955cf1a11375ee70599b98.

**Comment by jjallaire** [comment]
It's now in the updated Preview build (v0.99.853)

**Comment by hadley** [comment]
Awesome - thanks JJ!

**Comment by jeroenooms** [comment]
Maybe it would be a good idea to have rstudio automatically set the `askForPassword` function as an `option` in the same spirit as `options("viewer")`? E.g. `options(askpass = rstudioapi::askForPassword)` or so?

Thereby packages can easily find or set the password utility using `getOption("askpass")` without implementing front-end specific availability checks. It might also set a precedent if other GUI's want to provide a password entry utility such as gpg pinentry.

**Comment by jjallaire** [comment]
Good idea, done!

**Comment by jeroenooms** [comment]
Thanks. One final request: currently the `askForPassword` utility makes it impossible to enter no password. Would it be hard to not enforce this? Sometimes we specifically want to leave the password blank.

**Comment by jjallaire** [comment]
That is a little bit involved given where we are at in the release (just
about to close down) b/c there are 3 implementations I need to change with
this behavior (web, cocoa webkit, and qt webkit). We'll do this in the next
release though.

**Comment by sanjmeh** [comment]
Not sure if this issue belongs here ( I am a newbie to R but am catching up fast). The password window gets hidden behind (I use MAC OS Sierra) when I use the below code. Quite annoying as the browser window comes up on shiny with a blank screen waiting for the password while the user thinks that the database loading is taking mor then desired time only to find that there is a password window hiding behind. Can we change this behaviour to get the password window always on top?

` rstudioapi::askForPassword("enter password:")`

**Comment by jjallaire** [comment]
Are you calling this API from within a Shiny application or from within R code running within RStudio?

**Comment by sanjmeh** [comment]
I am calling this API from within Shiny. The password prompt comes over RStudio (which is ok) but the browser window that the ShinyApp opens overrides the prompt.

**Comment by jjallaire** [comment]
That API isn't supposed to run from within a Shiny application (as that
application won't have access to it if it runs from anywhere other than
RStudio). There is however a mode of Shiny application called Shiny gadgets
which runs *within* the RStudio window:
https://shiny.rstudio.com/articles/gadgets.html
