### ISSUE TITLE
NA's in document selection ranges

### ISSUE THREAD

**Issue by aoles** [rstudio/rstudioapi#103]
Hi,
I've noticed that the output of `getSourceEditorContext()$selection` might contain `NA`s  which is illustrated by the sample code below. After creating a file with the following content
```
abc
def
ghi
```
and selecting  the individual lines `rstudioapi::getSourceEditorContext()$selection` returns

```
Document Selection:
- [1, 1] -- [1, 4]: 'abc'
- [2, 1] -- [2, NA]: 'def'
- [3, 1] -- [3, NA]: 'ghi'
```
When I select the lines manually by dragging the mouse with ALT key pressed I get the expected result
```
Document Selection:
- [1, 1] -- [1, 4]: 'abc'
- [2, 1] -- [2, 4]: 'def'
- [3, 1] -- [3, 4]: 'ghi'
```
which indicates that there might be something funky going on with interpreting the `Inf`s.

Cheers,
Andrzej

**MWE:**
```r
individual_lines <- function() {
  n <- length(rstudioapi::getSourceEditorContext()$contents)
  Map(rstudioapi::document_range,
      Map(rstudioapi::document_position, 1:n, 1),
      Map(rstudioapi::document_position, 1:n, Inf)
  )
}

if(rstudioapi::isAvailable()){
  
  path <- tempfile()
  file.create(path)
  rstudioapi::navigateToFile(path)
  Sys.sleep(1)
  
  rstudioapi::insertText(location = rstudioapi::document_position(1, 1),
                         text = "abc\ndef\nghi")
  
  rstudioapi::setSelectionRanges(individual_lines())
  
  rstudioapi::getSourceEditorContext()$selection
}
```

**Comment by aoles** [comment]
Thanks a lot for addressing the problem so quickly!

BTW, some time ago a filed another issue in RStudio https://github.com/rstudio/rstudio/issues/2713 but haven't got any feedback on it yet. If you have a spare minute it would be great to hear your thoughts, maybe even this is something you might consider picking up on?

Cheers,
Andrzej

**Comment by kevinushey** [comment]
Just fixed up that one as well -- thanks for bringing it to my attention.

**Comment by aoles** [comment]
Awesome, many thanks Kevin!
