### ISSUE TITLE
showDialog without a url displays NA beneath the message

### ISSUE THREAD

**Issue by LucyMcGowan** [rstudio/rstudioapi#105]
If I use `showDialog()` without a url, it displays `NA` beneath the message, however the docs say the url is optional.

```
rstudioapi::showDialog(title = "Dialog", message = "message")
```
<img width="404" alt="image" src="https://user-images.githubusercontent.com/8431897/42188229-a397d618-7e18-11e8-891d-7a5f703f3911.png">

**Comment by kevinushey** [comment]
Thanks for the bug report! I've fixed this up in the development version of `rstudioapi` but will try to work around this issue in RStudio as well.

**Comment by LucyMcGowan** [comment]
Ah I should have checked the dev version 🙈 thanks, @kevinushey!

**Comment by kevinushey** [comment]
Ah, no! I only just fixed it just now in response to your reported issue 😄

**Comment by LucyMcGowan** [comment]
Oh perfect, thank you!
