### ISSUE TITLE
feature request: project_file()

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudioapi#11]
Triggered by the addition of `devtools::package_file()` (https://github.com/hadley/devtools/issues/985), which builds paths relative to a package's top-level directory.

It would be extremely useful to have something analogous for Projects that aren't an R package: `project_file()`, which would build paths relative to the Project's home directory.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudioapi/commit/b1c778908b245434bd27c65342a7c404af11d4d5
