### ISSUE TITLE
selectFiles not showing files

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudioapi#117]
It seems that in version 0.8 `selectFiles` misses most file types when not setting an explicit filter. See example below. Here `selectFiles` doesn't pickup any of the files in the `test/` directory although you can see those files in the Rstudio filebrowser

![image](https://user-images.githubusercontent.com/2998956/48297428-5b9dea00-e45c-11e8-947e-0bbe8bc79103.png)

**Comment by kevinushey** [comment]
Thanks! Fixing this will require changes on the IDE side so I've filed this here: https://github.com/rstudio/rstudio/issues/3881.
