### ISSUE TITLE
provide 'sendToConsole' helper

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudioapi#12]

**Comment by jrowen** [comment]
I'd also find this useful, especially if there was an option to automatically execute the code sent to the console.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rstudioapi/commit/757b0e54d6d28d3c4d5c0d7488aca00161a2d67d

**Comment by jjallaire** [comment]
@kevinushey I committed a slightly different version of this which exposes only the `execute` parameter (I didn't want addins to be able to execute things in the console without a user-visible artifact and the `focus` parameter didn't appear to actually work.

**Comment by kevinushey** [comment]
Sounds good to me -- thanks JJ!

**Comment by jrowen** [comment]
Works great!  Thanks.
```
devtools::install_github("jrowen/rhandsontable", ref="addin")
```
See the 'Edit a Data Frame' addin--big thanks to the `subsetAddin` example.

**Comment by jjallaire** [comment]
Awesome!

**Comment by jrowen** [comment]
When do you plan to release the next version of this library?  I'd like to push an update to CRAN that requires `rstudioapi::sendToConsole`.  Thanks.

**Comment by jjallaire** [comment]
It's now been pushed to CRAN.
