### ISSUE TITLE
Expose spelling dictionary search path 

### ISSUE THREAD

**Issue by jeroen** [rstudio/rstudioapi#123]
This [blog post](https://support.rstudio.com/hc/en-us/articles/200551916-Spelling-Dictionaries) explains where Rstudio expects the built-in as well as user defined spelling dictionaries.

It would be useful to expose this search path so that the `spelling` package can find these same dictionaries. Thereby the user can use the same dictionary in the IDE as well as `spelling` package. Currently we use a hack like this to find the built-in dictionary:

```r
list.files(file.path(dirname(Sys.getenv("RMARKDOWN_MATHJAX_PATH")), "dictionaries"))
```

This is obviously a hack which might break one day, and does not tell us where the user dictionaries are stored.

**Comment by kevinushey** [comment]
Now implemented in development version of `rstudioapi` with supporting functions in RStudio coming in the next daily builds.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudioapi/commit/84e061f192564daa9cc53927c52429e0c41d3b83
