### ISSUE TITLE
Trigger refresh in the Git pane

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudioapi#129]
In, e.g., usethis, we create and checkout branches in the current Project. This can lead to a temporary mismatch between the true git status, esp. current branch, and what RStudio's Git pane shows.

I'd love an rstudioapi function that did same as clicking on the "refresh" arrows in the Git pane.

**Comment by jmcphers** [comment]
@jennybc This is now possible with the development versions of rstudio and rstudioapi as follows:

    rstudioapi::executeCommand("vcsRefresh")

**Comment by jennybc** [comment]
@jmcphers What will this do in non-development versions of rstudio, i.e. how do I use this safely knowing that it will be a long while before the "typical" user's context supports it?

**Comment by jennybc** [comment]
I am used to using `rstudioapi::hasFun()` like this, to check that (1) tthe IDE is running and (2) rstudioapi has the function in question (`executeCommand`, here). I was worried about the version of RStudio itself. But from reading the PR, I think I get the lay of the land now.

**Comment by jmcphers** [comment]
Yes, you shouldn't have to worry about the specific version of RStudio (just whether or not it has executeCommand).
