### ISSUE TITLE
Detect when user focus is on console

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/rstudioapi#13]
Is there a way to determine, within an Addin function, when the user's cursor is in the console?

When run from the console, `rstudioapi::getActiveDocumentContext()$id` returns `"#console"`.  But when the same function is called from within an Addin function in a package, it will course return the id of the active open document.

Such detection would be useful in conjunction the proposed [sendToConsole helper](https://github.com/rstudio/rstudioapi/issues/12).

**Comment by kevinushey** [comment]
This is a bug in the focus tracking within RStudio, which we hope to fix soon. You can see a bit more discussion here, alongside a couple newly-proposed APIs: https://github.com/rstudio/rstudio/pull/558

**Comment by homerhanumat** [comment]
Yes, thanks for the reference.

**Comment by kevinushey** [comment]
This should be resolved now (please open a new issue if you're still having trouble)
