### ISSUE TITLE
Link the pkgdown site?

### ISSUE THREAD

**Issue by apreshill** [rstudio/rstudioapi#131]
The `pkgdown` site link is: https://rstudio.github.io/rstudioapi/

Would it be possible to make this link public, perhaps at the top of the GitHub repo or in the README?

**Comment by andrie** [comment]
Yes, please, and also automatically build the `pkgdown` site on Travis.

**Comment by hadley** [comment]
`usethis::use_pkgdown_travis()` will do 95% of the work

**Comment by andrie** [comment]
We can now close this issue. The `pkgdown` site has been updated and the link is on the top of the github repo.

https://rstudio.github.io/rstudioapi/
