### ISSUE TITLE
Save all open documents

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#14]
So (e.g.) devtools functions can trigger the save even when not called with the keyboard shortcut.

**Comment by gaborcsardi** [comment]
:+1: 

It would be also handy to be able to tell if the current editor windows needs saving. (Before I start working with the potentially unsaved file in an addin.)

**Comment by kevinushey** [comment]
I think implementing this implies a couple APIs we might want to implement:

```R
documentList()            # list documents open in IDE
documentCreate()          # same behavior as 'file.edit()'?
documentSave(id = ...)    # save one or more documents
documentClose(id = ...)   # close one or more documents
documentSaveAll()         # save all documents
documentCloseAll()        # close all documents
```

@hadley can you weigh in?

**Comment by hadley** [comment]
That sounds great! Not sure if documentCreate is needed.

**Comment by kevinushey** [comment]
I imagine it's okay to leave untitled documents out of this for the save request? (Ie we just want to make sure any modified package files open in RStudio are saved before executing a devtools action)

**Comment by jjallaire** [comment]
Yes, in the save all files before build we do indeed exclude untitled
documents
