### ISSUE TITLE
Get job state / post-job hook

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudioapi#144]
Currently, one can set job states, status, etc., with function luke rstudioapi::setJobState(). However, one can not retrieve them as far as I can tell. I would like a getJob() or getJobs() function akin to those functions for launcher jobs. 

It seems this is available with hidden IDE function `.rs.invokeRpc("get_jobs")`.

My use-case is writing some wrappers to alert me to the status of jobs running on my server (with RPushbullet).

It would also be helpful to have a post-job hook akin to `stop` or `info` in `jobAdd()` that could define a function (taking the script name and results environment as an argument) to run after a job defined with `jobAdd()` or `jobRunScript()`.

**Comment by AshesITR** [comment]
I would also like this feature.
My usecase is starting a Net of jobs, some of which wait for other jobs to complete and generate some artifacts (RDS) upon which the downstream jobs depend.

**Comment by Erinaceida** [comment]
after almost five years has this still not been added?

**Comment by kevinushey** [comment]
Sorry for the wait -- this is now available in the latest daily builds of RStudio + the development versions of `rstudioapi`.
