### ISSUE TITLE
Given a path: Open it in the file pane

### ISSUE THREAD

**Issue by oliverroc** [rstudio/rstudioapi#145]
It would be great if there exists a function for the rstudioapi that given a particular path it opens in the file pane. 

Sometimes I use list.files/list.directories in my code in orther to see if certain files or directories where properly created, but the output in the console is not very user friendly :p :p that's why I think this would be a nice feature to have!

If been trying to find if there exists such a functionality without success. I came across with rstudioapi. I hope is the proper place to request for such a functionality, thanks.

Thanks

**Comment by ProdigiosaLadybug** [comment]
Yes! It would be super useful!

**Comment by gadenbuie** [comment]
While I'd love a `"goToSourceDir"` command ([e.g. for this RStudio feature request](https://github.com/rstudio/rstudio/issues/6781)), I was able to use the hints from your code in #148 to come up with the following that I keep in my `~/.Rprofile`:

```r
if (
  interactive() && 
  all(vapply(c("rstudioapi", "later", "fs"), requireNamespace, quietly = TRUE, FALSE))
) {
  .browse_source_dir <- function(path = NULL) {
    if (!rstudioapi::hasFun("executeCommand")) return(invisible())
    if (is.null(path)) {
      path <- rstudioapi::getSourceEditorContext()$path
    }
    if (fs::is_file(path)) {
      path <- fs::path_dir(path)
    }
    if (!fs::dir_exists(path)) {
      message("Directory does not exist: ", path)
      return(invisible())
    }
    owd <- setwd(path)
    later::later(function() {
      rstudioapi::executeCommand("goToWorkingDir")
      setwd(owd)
    })
  }
}
```

**Comment by oliverroc** [comment]
I haven't had time until now to check this out!

It's exactly what I was looking for!

Still much to learn!
