### ISSUE TITLE
Feature request: closeProject()

### ISSUE THREAD

**Issue by djnavarro** [rstudio/rstudioapi#149]
Similar to the question linked below, there are cases where I want to programmatically close an RStudio project *without* opening a new one, similar to the "close project" menu option. There are cases where a function needs to switch from one task that *is* an RStudio project to another one that is not, and it's less than ideal to leave the old project open. As far as I can tell this is not currently possible? 

https://stackoverflow.com/questions/50446677/closing-an-rstudio-project-programmatically

**Comment by mrchypark** [comment]
You can use function below work similar.
```
rstudioapi::executeCommand("closeProject")
```

**Comment by djnavarro** [comment]
Perfect thank you!
