### ISSUE TITLE
Close an open document

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#15]
So you can open a file, prompt the user to do something, then close it when they're done

**Comment by kevinushey** [comment]
Tracking these tasks in #14 now.

**Comment by dpprdan** [comment]
Has this actually been implemented in #14? I see `documentSave` but no `documentClose` or similar. Or am I missing something?

**Comment by kevinushey** [comment]
Oops, you're right -- we never did implement `documentClose()`.

Do you have a specific use case in mind for `documentClose()`?

**Comment by dpprdan** [comment]
My specific use case are the tests in the [remedy](https://github.com/ThinkR-open/remedy) 📦, where some files are opened with `rstudioapi::navigateToFile()`, then edited in some way, but cannot be closed automatically upon completion of the test. 
Note that I am not the maintainer of the package, so @yonicd or @ColinFay may be able to add some more context.

**Comment by yonicd** [comment]
that and a function to switch the focus to a different open source tab would be very helpful. there is no way to switch tabs when they are untitled, only files on disk can be focused by navigateToFile.
