### ISSUE TITLE
launcherResourceLimit does not pass args to 'callLauncherFun'.

### ISSUE THREAD

**Issue by bschulth** [rstudio/rstudioapi#164]
launcherResourceLimit does not pass args to 'callLauncherFun'.  This results in errors:

> rstudioapi::launcherResourceLimit("memory", "16000")
Error in .rs.scalar(type) : argument "type" is missing, with no default

See: https://github.com/rstudio/rstudioapi/blob/master/R/launcher-functions.R#L149

launcherResourceLimit <- function(type, value) {
  callLauncherFun("launcher.newResourceLimit")
}

**Comment by kevinushey** [comment]
Thanks for the bug report! Should be fixed up on master now.
