### ISSUE TITLE
documentNew has different formals when called via :: than when found via findFun

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rstudioapi#167]
I may not be using `findFun()` as intended, but I was expecting that I could call a function found with `rstudioapi::findFun("fn")` in the same way as if I had called the function with `rstudioapi::fn()`.

In my specific case, I tried using `text` (as in the formals of `rstudioapi::documentNew()`) but the argument is called `code` in the found function. I also noticed that `position` gets expanded into two arguments when found.

```
> formals(rstudioapi::documentNew)
$text


$type
c("r", "rmarkdown", "sql")

$position
document_position(0, 0)

$execute
[1] FALSE
 
> documentNewFound <- rstudioapi::findFun("documentNew")
> formals(documentNewFound)
$type


$code


$row
[1] 0

$column
[1] 0

$execute
[1] FALSE
```

**Comment by gadenbuie** [comment]
Oh, actually I ran into this by trying to replace

```r
rstudioapi::documentNew(text = "# hello")
```

with

```r
rstudioapi::callFun("documentNew", text = "#hello")
```

**Comment by kevinushey** [comment]
Right, that's unfortunately not true for some functions (like `documentNew()`) which are not just simple pass-through shims.

**Comment by gadenbuie** [comment]
Makes sense. It might be helpful to mention in the docs of `callFun()` and `findFun()` that some functions called/returned by those methods are different than their exported counterparts.
