### ISSUE TITLE
(Re-)launch a Project?

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudioapi#18]
Could `rstudioapi` offer a function that launches an RStudio session in a Project? I.e. you provide path to an `.Rproj` file and it's as if you did _File > Open Project ..._.

You could use this after `devtools::create()`, for example. Or to relaunch the current project after adding important infrastructure that changes the IDE (e.g., add package infrastructure or make it a git repo or create a Makefile).

I tried `navigateToFile()` but that just opens `.Rproj` for editing.

**Comment by kevinushey** [comment]
This sounds like it'd be handy. What about something like:

    rstudioapi::createProject(path = "")
    rstudioapi::openProject(path = "", newSession = "")

**Comment by jennybc** [comment]
I have been wondering exactly what constitutes a valid `.Rproj` file. So far I have just modified [what I found in `devtools`](https://github.com/hadley/devtools/blob/master/inst/templates/template.Rproj). An official function to create `.Rproj` would feel better.

**Comment by 0tertra** [comment]
would be very useful indeed had the same [Feature Request](https://support.rstudio.com/hc/en-us/community/posts/208561188-managing-projects-with-commands-)

**Comment by jennybc** [comment]
I just stumbled across an option to reload `.Rproj` by control clicking it. That's basically what I want, but available via rstudioapi.

But here's the weird thing with that: make a new Project in a new directory. Make it an R package via `devtools::setup()`. Make it a git repo via `devtools::use_git()`. Reload `.Rproj` via the control click method described above. The new RStudio session has a Build pane, but not a Git pane. Quit RStudio and relaunch Project by double-clicking in Finder. Git pane appears.

**Comment by thercast** [comment]
Just wanted to chime in and say having functions like `rstudioapi::createProject()` and `rstudioapi::openProject()` functions would be extremely useful.  For example I could have my shiny app create an accompanying project for the user to interact with key objects created in their use of the app, and they could easily open the project in RStudio to do further customization of these objects should they wish to do so.  Combined with the project [templates](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html) this has a lot of potential.

**Comment by jennybc** [comment]
Something @hadley shared with me since I opened this is that you can launch a Project with:

``` r
browseURL("path/to/your_project.Rproj")
```

**Comment by kevinushey** [comment]
Would you ever want to be able to create a `.Rproj` file without immediately opening that directory as an RStudio project after? (Is it okay if `createProject()`, `openProject()` both immediately open that project in RStudio?)

Or do we want something like `initializeProject()` that only writes out the `.Rproj` file?

**Comment by hadley** [comment]
Creating a project file by hand is already easy. I'm most interested in the launching
