### ISSUE TITLE
callRemote fails on second call in subprocess

### ISSUE THREAD

**Issue by AshesITR** [rstudio/rstudioapi#186]
The IPC request and response files are static.
That means, polling for file.exists(response) in https://github.com/rstudio/rstudioapi/blob/aa176307adf71b0fa5308961606497c5ae0a7439/R/remote.R#L42 immediately breaks on all calls made after the first.

The result is that the API return value is always the same.

A trivial fix is deleting the response file before issuing a new IPC request.
Adding `file.remove(response)` at https://github.com/rstudio/rstudioapi/blob/aa176307adf71b0fa5308961606497c5ae0a7439/R/remote.R#L28 fixes the issue.

Repro:

Source as local job and examine the results:

*Failing script*

```r
call0 <- rstudioapi::isAvailable(child_ok = TRUE)
call1 <- rstudioapi::getActiveProject()
```

*Working script (using a manual patch)*

```r
ns <- getNamespace("rstudioapi")
unlockBinding("callRemote", ns)
ns$callRemote <- function (call, frame) {
  request <- Sys.getenv("RSTUDIOAPI_IPC_REQUESTS_FILE",
                        unset = NA)
  response <- Sys.getenv("RSTUDIOAPI_IPC_RESPONSE_FILE",
                         unset = NA)
  secret <- Sys.getenv("RSTUDIOAPI_IPC_SHARED_SECRET",
                       unset = NA)
  if (is.na(request) || is.na(response) || is.na(secret))
    stop("internal error: callFunRemote() called without remote connection")
  attr(call, "srcref") <- NULL
  if (is.name(call[[1L]]))
    call[[1L]] <- call("::", as.name("rstudioapi"),
                       call[[1L]])
  for (i in seq_along(call)[-1L]) call[[i]] <- eval(call[[i]],
                                                    envir = frame)
  if (file.exists(response)) file.remove(response)
  data <- list(secret = secret, call = call)
  tmp <- tempfile(tmpdir = dirname(request))
  saveRDS(data, file = tmp)
  file.rename(tmp, request)
  now <- Sys.time()
  repeat {
    if (file.exists(response))
      break
    diff <- difftime(Sys.time(), now, units = "secs")
    if (diff > 10)
      stop("RStudio did not respond to rstudioapi IPC request")
    Sys.sleep(0.1)
  }
  response <- readRDS(response)
  if (inherits(response, "error"))
    stop(response)
  response
}
environment(ns$callRemote) <- ns
lockBinding("callRemote", ns)

call0 <- rstudioapi::isAvailable(child_ok = TRUE)
call1 <- rstudioapi::getActiveProject()
```

**Comment by kevinushey** [comment]
Thanks for the bug report -- I believe this is fixed now via https://github.com/rstudio/rstudioapi/commit/ed5dd255bc48a3b414ce517c8111d3fbda023955#diff-368a37978565327a8daed70334ed17c4R16. Do you still see this issue in the development version of `rstudioapi`?

**Comment by AshesITR** [comment]
Thanks for suggesting the dev version, I must have viewed the wrong branch in github.
The bug is already fixed in the current dev version.
