### ISSUE TITLE
new feature request: rstudioapi::askForPassword() caches response for session or time duration

### ISSUE THREAD

**Issue by schnee** [rstudio/rstudioapi#192]
Could askForPassword _safely_ cache a previously given password and not challenge the user if the cache has not expired? It would probably need a cache-key parameter of some sort so that it would know if the response is in the cache.

During interactive sessions, constantly supplying the password is a little inefficient (but I understand the security reasons for this) as I close my DB sessions as soon as I'm done with them in a given execution; I frequently need to re-open them while developing.

**Comment by AshesITR** [comment]
Have you taken a look at `rstudioapi::askForSecret()`?
That function has the ability to use `keyring` to store supplied credentials.

**Comment by schnee** [comment]
rstudioapi::askForSecret looks like it might do the tric. thanks. closing.
