### ISSUE TITLE
Embeded iframe in rstudio viewer

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudioapi#2]
I'm working on [plotly's R package](https://github.com/ropensci/plotly) and thought it'd be neat to embed plotly graphs in the rstudio viewer via an `<iframe>`, but the content doesn't seem to load in the viewer:

``` r
tmp <- tempfile(fileext = ".html")
curl::curl_download("https://gist.githubusercontent.com/cpsievert/f244be845a5cd13eb4e4/raw/9c1633978da3a22ec95dcf7e3af797607bf77a82/index.html", tmp)
rstudioapi::viewer(tmp)
```

However, it loads for me on Chrome/Firefox:

``` r
browseURL(tmp)
```

cc @mkcor @chriddyp

**Comment by jjallaire** [comment]
That's correct. The viewer doesn't support external URLs. This is a
security precaution as we don't want arbitrary external web content to be
loadable within the IDE frame. One possible workaround is sandboxing the
iframe, however the desktop browser toolkit we currently use doesn't
support iframe sandboxes.

**Comment by cpsievert** [comment]
Ah, OK, thanks for the quick response JJ!

**Comment by gaborcsardi** [comment]
I don't want to revisit this, just want to mention the most browsers support the `srcdoc` attribute of `<iframe>`, and then all data is embedded, so if this is supported in the viewer, then it is a way to put in an `<iframe>`.
