### ISSUE TITLE
Blank Password

### ISSUE THREAD

**Issue by wrathematics** [rstudio/rstudioapi#20]
Currently, `askForPassword()` returns `NULL` when both the cancel button is pressed and when an empty password (`""`) is entered.  Any chance the blank password could be changed to return `""` ?

It may also be handy to have an option to disallow blank passwords (see https://github.com/wrathematics/getPass/issues/6).  This can be emulated on our end with something like (assuming blank passwords return `""`)

``` r
pass <- ""
while (pass == "")
  pass <- rstudioapi::askForPassword("")
```

but it's a little clumsy, since the password box drops out and reappears each time.

**Comment by hadley** [comment]
I can't currently reproduce this - you now get an error if you empty a blank password.

**Comment by wrathematics** [comment]
Same behavior as before for me with latest RStudio and gh version of rstudioapi.

![pass](https://cloud.githubusercontent.com/assets/2561297/26648308/0ff4c4de-4610-11e7-9695-403c6567e24d.png)

**Comment by hadley** [comment]
You don't see this?

<img width="401" alt="screen shot 2017-05-31 at 1 53 05 pm" src="https://cloud.githubusercontent.com/assets/4196/26648557/7ceb94da-4608-11e7-8908-d99cd325f638.png">

If not, it's possibly fixed in a daily.

**Comment by wrathematics** [comment]
Installed the latest daily build and that is indeed what I see.

Thanks!
