### ISSUE TITLE
Add function for specifying Files pane location

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudioapi#204]
Add the ability to programmatically specify the location shown in the Files pane. Perhaps something like
```r
rstudioapi::filesPane(path = "~")
```

**Comment by blairj09** [comment]
@kevinushey I downloaded the latest version of the package from GH and see the `filesPaneNavigate()` function. However, when I try to use it I get the following:
```r
rstudioapi::filesPaneNavigate("~")
#> Error: Function filesPaneNavigate not found in RStudio
``` 

This is with RStudio Desktop Pro Version 1.4.940-1

**Comment by kevinushey** [comment]
I think we don't have Pro builds with this particular API just yet -- should hopefully be coming soon (1.4.950+)

**Comment by blairj09** [comment]
Confirmed this is working with the latest dailies. It would be nice if there was an optional argument to activate the files pane as well:

```r
rstudioapi::filesPaneNavigate("~", show = TRUE)
```
