### ISSUE TITLE
rstudioapi::getActiveProject() in a shiny gadget

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudioapi#22]
When called from a shiny gadget rstudioapi::getActiveProject() give the project directory of the gadget. It would useful to determine the project directory of the current project where the gadget was called. E.g., lets say the gadget is called gitgadget and the current project is in c:\myprojects\project-a. rstudioapi::getActiveProject()  will return something like c:\myprojects\gitgadget rather than c:\myprojects\project-a when you open the gadget while working on project-a

**Comment by kevinushey** [comment]
Is that really the case? `getActiveProject()` should return the directory of whatever the active RStudio project is; it should be independent of the gadget altogether.

**Comment by vnijs** [comment]
It was when I posted this issue but not anymore. Should have closed. Thanks
