### ISSUE TITLE
Links are broken in html in See Also section on https://rdrr.io/

### ISSUE THREAD

**Issue by datakid** [rstudio/rstudioapi#239]
When using the rdrr.io documentation with a customer - [this page specifically](https://rdrr.io/cran/rstudioapi/man/launcherSubmitJob.html), but I presume it's a general problem - I noticed that the links at the bottom of the page have been rendered with the braces included:

eg: https://rdrr.io/cran/rstudioapi/man/launcherConfig().html

The braces 404 the link. Removing the braces are sufficient to fix the links:

https://rdrr.io/cran/rstudioapi/man/launcherConfig.html

https://github.com/rstudio/rstudioapi/blob/96fad1d75b5cacd9a0fe9ff7f58d140f5cf4300b/man/launcherSubmitJob.Rd#L98-L102

I didn't write a pull request because every page in this directory would need to be updated, and I don't know if this issue is related to the build process - ie, is this issue an artefact of the md-> man page build.

**Comment by jgutman** [comment]
We could work around this in the `rstudioapi` documentation, but this appears to be an issue with roxygen2, that was introduced when we use the `@family` tag. This is not essential to resolve immediately
