### ISSUE TITLE
name changed to positapi

### ISSUE THREAD

**Issue by waynelapierre** [rstudio/rstudioapi#263]
Will the name be changed to positapi given that RStudio will be rebranded as Posit?

**Comment by kevinushey** [comment]
No, as the IDE's name will remain as RStudio.

**Comment by waynelapierre** [comment]
I thought the IDE name will be changed to Posit. So, it is only the company name that will be changed to Posit?

**Comment by kevinushey** [comment]
As I understand it, the company name will change, and (I believe) some of the professional product names may change, but the IDE itself will continue to be called RStudio.
