### ISSUE TITLE
Access file and directory selection dialogs

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#27]
Compared to `file.choose()` these would allow you to:

- Set the starting directory

- Select directories, rather than files

- Optionally, operate like a save dialog where you can enter a file name

**Comment by kevinushey** [comment]
Can you elaborate a bit on why the save dialog would be useful here?

I agree that `rstudioapi::openFile()` would be useful for selecting one or more files using the system dialog (or web dialog for RStudio Server)

**Comment by hadley** [comment]
Sometimes you want to ask people where they'd like to create a file and what to call it. (As opposed to electing an existing file)

**Comment by vnijs** [comment]
Access to the Data Import dialog, Spark connection dialog, and (future) DB connection dialogs would also be wonderful
