### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hermanndallinger** [rstudio/rstudioapi#270]
Hi,

I am running Rstudio on a Linux machine with a Hybrid processor core, meaning I have a two performance cores with two threads each, and 8 somewhat slower cores i7-1255U × 12.
I managed to move the Rsession to one of the performance cores using `taskset -pc 0 pid`, however, I do have to manually look up the pid each time and of course it changes. Is there a way to extract the session pid using rstudioapi or do you think it would be possible to implement the core switching feature?

Best Hermann

**Comment by lpiep** [comment]
Hi Hermann, would base R's `Sys.getpid` solve your problem?

**Comment by hermanndallinger** [comment]
> Hi Hermann, would base R's `Sys.getpid` solve your problem?

Thanks a ton, that's all I need. Seems like I was looking at the wrong place. Best Hermann
