### ISSUE TITLE
FR: getDocumentContent()

### ISSUE THREAD

**Issue by olivroy** [rstudio/rstudioapi#281]
Hi, I was wondering if it was possible to add getDocumentContent()

For unsaved files, I don't know how to read lines

or readDocumentLines

**Comment by kevinushey** [comment]
Does `rstudioapi::getSourceEditorContext()` give you what you need? You can pass it an `id` as retrieved from `rstudioapi::documentId()`.

**Comment by olivroy** [comment]
Oh, yes sorry. I didn't realise it returned a list. This does the trick indeed.
```r
rstudioapi::getSourceEditorContext()$content
```
