### ISSUE TITLE
`isAvailable()` returns `TRUE` in Positron

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/rstudioapi#302]
The documentation for `rstudioapi::isAvailable()` says:

> Check if RStudio is running.

But that function returns `TRUE` when called in Positron.

<img width="953" alt="Screenshot 2024-07-04 at 8 00 30 PM" src="https://github.com/rstudio/rstudioapi/assets/987057/e3e16f82-672c-47c8-90a2-b0a8ea93573d">

**Comment by gadenbuie** [comment]
The docs for `rstudioapi::isAvailable()` were accurate back when rstudioapi was only useful in RStudio, but it now has counterpart uses in both VS Code and Positron. A more up-to-date description of `isAvailable()` would be "Check if running in an R session with access to an IDE with rstudioapi support."

For availability of specific functions, I recommend using `rstudioapi::hasFun()` to test if the IDE supports the function you want to use. 

Here's the output of both functions in Positron:

```r
rstudioapi::isAvailable()
#> [1] TRUE
rstudioapi::hasFun("viewer")
#> [1] FALSE
```

Whereas in RStudio...

```r
rstudioapi::hasFun("viewer")
#> [1] TRUE
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the clarification and for the suggestion. Very useful!

I'll leave this issue open in case you need a reminder to update the docs, but feel free to close if you think that is more appropriate.

**Comment by kylebutts** [comment]
Should `rstudioapi::hasFun("viewer")` return `TRUE` since positron has `getOption("viewer")`?

**Comment by gadenbuie** [comment]
> Should rstudioapi::hasFun("viewer") return TRUE since positron has getOption("viewer")?

I think that's a good sign that it will eventually return `TRUE`, but until `rstudio::viewer()` is wired up in Positron, `rstudioapi::hasFun("viewer")` should return `FALSE` to help avoid the error seen in the linked post.
