### ISSUE TITLE
Recent changes to `getVersion()` cause some RStudio addins to fail in Positron

### ISSUE THREAD

**Issue by ateucher** [rstudio/rstudioapi#307]
I use `codegrip::addin_reshape()` and `styler:::style_active_file()` in both RStudio and Positron (bound to keyboard shortcuts). Both of these functions call `rstudioapi::modifyRange()`, which in turn calls `rstudioapi::getVersion()`.

Recent changes in 3bd91a6c202c356eca7364282d9213aba3bf9924 and 6a71e697c5dc3d01384555f78e6cd87721a84e15 mean that `getVersion()` fails outside of RStudio:

In Positron:

``` r
rstudioapi::modifyRange(Map(c, 1:5, 1), paste0("#", sample(letters, 5), " "))
#> Error in base$.Call("rs_rstudioVersion", PACKAGE = "(embedding)"): "rs_rstudioVersion" not available for .Call() for package "(embedding)"

rstudioapi::getVersion()
#> Error in base$.Call("rs_rstudioVersion", PACKAGE = "(embedding)"): "rs_rstudioVersion" not available for .Call() for package "(embedding)"
```

<sup>Created on 2024-10-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I don't think these addins are officially supported in Positron, but I know there has been some work to ensure a certain subset of rstudioapi functions work in Positron, including `modifyRange()` (e.g., https://github.com/posit-dev/positron/issues/1312 and https://github.com/posit-dev/positron/pull/2582).

Apologies if this should be a Positron issue rather than rstudioapi.

Thanks!

**Comment by ateucher** [comment]
Reported in Ark, as I believe that's a better place for this

**Comment by kevinushey** [comment]
Thanks! I followed up with the ark team as well; they'll be implementing the necessary APIs on their side as well.
