### ISSUE TITLE
Need rstudioapi::deleteRange()

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/rstudioapi#31]
Using modifyRange() you can blank out a line by setting the text in range to `""`. Unfortunately there is no way to delete lines. For addins that use the API to transform user's code this will likely mean they end up creating blank lines the user has to clean up manually.  

See the gif  in the readme at https://github.com/MilesMcBain/packup for an example of where the ability to delete lines would improve the user experience.

**Comment by kevinushey** [comment]
Perhaps I'm misunderstanding what you're looking for, but `modifyRange()` should do what you need here with an appropriately-constructed range.

For example, to delete lines 2 through 4 in a document, you could use something like:

```R
rstudioapi::modifyRange(c(2, 0, 5, 0), "")
```

Does this do what you need?

**Comment by MilesMcBain** [comment]
Sort of! I guess I never tried 0 indexing, so that's my bad, sorry.

The problem I have now is if I supply a list of `document_range` objects the line deletion does not work completely for moderately large lists. My guess would be that some kind of loop over the list gets itself in a tangle with a document that is being updated sequentially and position references becoming stale/invalid.

This code will reliably reproduce the issue on my machine
```
library(rstudioapi) #dont delete me
#delete me start


























#delete me end
#don't delete me 2
replace_location_starts <- mapply(rstudioapi::document_position, 2:29, 0, SIMPLIFY = FALSE)
replacte_location_ends <- mapply(rstudioapi::document_position, 2:29 + 1, 0, SIMPLIFY = FALSE)
replace_range_list <- mapply(rstudioapi::document_range, replace_location_starts, replacte_location_ends, SIMPLIFY = FALSE)
rstudioapi::modifyRange(location = replace_range_list, "")
```
The result of running the code is:
```
library(rstudioapi) #dont delete me













#delete me end
replace_location_starts <- mapply(rstudioapi::document_position, 2:29, 0, SIMPLIFY = FALSE)
replace_range_list <- mapply(rstudioapi::document_range, replace_location_starts, replacte_location_ends, SIMPLIFY = FALSE)
```
This has a race condition smell about it and my machine is pretty slow, so if you can't reproduce try increasing the number of lines to be deleted.

**Comment by kevinushey** [comment]
Nice catch! This is indeed a bug in how RStudio attempts to modify a list of ranges -- unfortunately, we run the operations sequentially from start to end, so the later ranges in the list become 'invalid' after their application.

This will be fixed in the next daily builds of RStudio.

**Comment by kevinushey** [comment]
Okay, I think this should be properly handled now, although for deletion of multiple ranges you'll have to try installing the latest daily builds of RStudio.
