### ISSUE TITLE
Function to distinguish Positron and RStudio

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/rstudioapi#310]
As a package developer, I would find it very useful to have a function that allows me to distinguish between IDEs like Positron and RStudio.

For instance, Positron does not support inline display of tables in Quarto notebooks, whereas RStudio does. So a table-drawing package needs to behave differently and only tables in the viewer when in Positron.

Currently, we can hack our way there by checking if some function is available (ie: generates an error), but those solutions feel hacky.

Unless there is 100% feature parity between editors, it will likely always be useful for developers to know where things are run.

Thanks for considering!

Related to: https://github.com/rstudio/rstudioapi/issues/302

**Comment by gadenbuie** [comment]
There are `RSTUDIO` and `POSITRON` environment variables that you can consult that are each set with the context of the respective IDEs. They're briefly mentioned in an example here: https://positron.posit.co/extensions.html#compatibility

**Comment by vincentarelbundock** [comment]
Thanks, this is exactly what I was looking for!

Sorry I missed this in the docs.
