### ISSUE TITLE
Provide simple key-value store in .Rproj.user

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudioapi#32]
To provide an easy way to persist data across sessions.

**Comment by jjallaire** [comment]
Done!

**Comment by hadley** [comment]
Awesome, thanks!  

(Does that commit include the R functions too? I don't see them, but maybe `.rs.addApiFunction()` creates them? Do they still need to be exported?)

**Comment by jjallaire** [comment]
They get exported over in the rstudioapi package:
https://github.com/rstudio/rstudioapi/commit/1ec57243e179e108e963dd24f74b63add3c05703

**Comment by hadley** [comment]
Ooops, totally confused about which repo I was looking in.
