### ISSUE TITLE
rstudioapi::getSourceEditorContext failing when executed from addin or console

### ISSUE THREAD

**Issue by useless5771** [rstudio/rstudioapi#40]
RStudio: 1.0.136 
rstudioapi 0.6 available on CRAN (	published on 2016-06-27 )

How to reproduce:
1. Open some files in RStudio.
2. Run 'rstudioapi::getSourceEditorContext()' in the console
3. The error is displayed:
> Error: 'x' should be a list of {range, text} pairs
i.e. as if there was no files opened in the editor at all.

Expected: return descriptor of currently viewed file in the editor.

The same error happens when 'rstudioapi::getSourceEditorContext()' is invoked from RStudio addin.

This issue appears to be fixed at revision bc145dd6734cba2d9f8d55ea4cdafa0bc126319f so this ticket is raised for future reference.

**Comment by jjallaire** [comment]
@kevinushey and @javierluraschi Are we ready to do a submission of rstudioapi to CRAN?

**Comment by javierluraschi** [comment]
I don't expect any more changes in rstudioapi, so yes.

**Comment by kevinushey** [comment]
I think we're ready as well.

**Comment by gtritchie** [comment]
I'm planning to add one more api, related to terminal. Let me know if I should get on that ASAP, or if it can wait another week.

**Comment by jjallaire** [comment]
This can wait another week so take your time on the terminal API.

**Comment by hadley** [comment]
Closing, since fixed in dev
