### ISSUE TITLE
Add functions for getting/setting Shiny viewer

### ISSUE THREAD

**Issue by wch** [rstudio/rstudioapi#54]
It would be useful to have functions to get and set the Shiny viewer setting -- that is, the setting that controls whether a Shiny app opens in the viewer pane, a viewer window, or an external browser. This would be useful for rstudio/shinytest#117.

Currently this can be done with `.rs.readUiPref("shiny_viewer_type")` and `.rs.writeUiPref`.

**Comment by vnijs** [comment]
I'm updating a several package for CRAN that that will use `.rs.readUiPref`. Running checks now gives the warning below:

```
checking foreign function calls ... WARNING
Foreign function call without 'PACKAGE' argument:
  .Call("rs_shinyviewer", ...)
```

Would be great to have this exported. Alternatively, is there a work-around you can suggest?

**Comment by samssann** [comment]
> Related request. It would be very useful to have an option to set the initial size for a Window showing a shiny app. You can set height for Viewer, and Height and Width for Dialog, but no options seem available to set the size of a Window.
> 
> https://shiny.rstudio.com/reference/shiny/1.0.5/viewer.html

This would indeed be a great and needed feature.

**Comment by jmcphers** [comment]
We now have `rstudioapi::readPreference` and `rstudioapi::writePreference` for this.
