### ISSUE TITLE
selectDirectory selects files, not directories

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudioapi#58]
Very happy to see the new `selectFile` and `selectDirectory` functions! However, I just tried out the `selectDirectory` on Mac and Windows and cannot get it to return a directory path. When I press the select button the file browser steps into the directory rather than returning the path. If I then select a file and press select I get the path to the file so it seems `selectDirectory` is doing `selectFile` instead.

Using Rstudio preview 1.1.359

**Comment by kevinushey** [comment]
Looks like this was a silly bug on our side. Thanks for reporting!
