### ISSUE TITLE
detect RStudio via "Knit HTML"?

### ISSUE THREAD

**Issue by jennybc** [rstudio/rstudioapi#7]
I'm using `rstudioapi::getVersion()` in an `.Rmd`.

It seems this only works if I render via `rmarkdown::render()` from R Console (in RStudio, obviously). I keep forgetting this and re-discovering that RStudio cannot be detected if I render via "Knit HTML". If `rstudioapi::getVersion()` appears in an R chunk, I merely get an error. But if it appears as inline R code, it actually prevents rendering.

Should or could RStudio be detected via "Knit HTML"?

**Comment by jjallaire** [comment]
The rstudioapi package relies on calling directly into RStudio (since all of it's functions rely on talking directly to RStudio internal functions), which of course isn't available during Knit HTML. So I don't think there is a straightforward way to make this work.

**Comment by jennybc** [comment]
ok
