### ISSUE TITLE
showPrompt() fails when more than one windows are open

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/rstudioapi#71]
I found `showPrompt()` attempts to pop up a prompt per window. But, It seems only the first popup is valid as it raises an error shown bellow for the second and the subsequent ones:

![image](https://user-images.githubusercontent.com/1978793/32320883-a255ceba-c002-11e7-9827-82d71b7dfd50.png)

**Comment by kevinushey** [comment]
Thanks! I've reproduced this; I've filed this issue on the IDE side, as this will need to be fixed in RStudio itself.

**Comment by yutannihilation** [comment]
Sure. Thanks for the confirmation :)

**Comment by dfalty** [comment]
@yutannihilation Thanks for the report! This should be fixed in the latest 1.2 RStudio build. I was able to verify this on 1.2.160.
https://dailies.rstudio.com/

**Comment by yutannihilation** [comment]
Thanks! Looking forward to the next release. 👍
