### ISSUE TITLE
getThemeInfo() can return editor = NULL and dark = NA

### ISSUE THREAD

**Issue by nicknimchuk** [rstudio/rstudioapi#73]
I haven't been able to reproduce this myself, but per this post in the RStudio Community:
https://community.rstudio.com/t/library-tidyverse-results-in-error-on-r-studio/2642/13

A call to `getThemeInfo()` can return:
```r
$editor
NULL

$global
[1] "Modern"

$dark
[1] NA
```

Given the fact that I can't reproduce it (and the one person on the community site that I was discussing it with fixed the problem), I'm unsure if it's an issue with the API or the IDE itself.

**Comment by kevinushey** [comment]
Sounds like this was fixed with https://github.com/rstudio/rstudioapi/pull/74?

**Comment by nicknimchuk** [comment]
https://github.com/rstudio/rstudioapi/pull/74 was closed without action, but the issue is taken care of upstream in https://github.com/rstudio/rstudio/pull/1741 (long term solution) and downstream in https://github.com/tidyverse/tidyverse/issues/88 (short term solution), so this can be closed.
