### ISSUE TITLE
rstudioapi::restartSession() does not clear environment or search in R3.4.4

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudioapi#95]
It seems that since R 3.4.4 `rstudioapi::restartSession()` backs-up (and restores) the current environment and doesn't unload packages. _Session > Restart R_ from the menu does still work as expected. Does Rstudio call a different function? Is there an option to have `rstudioapi::restartSession()` behave the same as the menu?

FYI settings:

![image](https://user-images.githubusercontent.com/2998956/39008014-54dca616-43bc-11e8-8522-07a66f1faacf.png)

**Comment by vnijs** [comment]
FYI Same issue in R 3.5

**Comment by kevinushey** [comment]
Thanks for the bug report! I've copied this over to the RStudio repository as we'll need some changes there to support this.

**Comment by geotheory** [comment]
This still seems to be unresolved. Is there any intention to offer a genuine session refresh?

```
> exists('slice')
[1] FALSE
> suppressMessages(require(dplyr, quietly = TRUE))
> iris |> slice(1)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
> rstudioapi::restartSession()

Restarting R session...

> exists('slice')
[1] TRUE
> iris |> slice(1)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa

```

**Comment by kevinushey** [comment]
Sorry for taking so long to respond.

I think `rstudioapi::executeCommand("restartR")` should do what you need -- it invokes the same command as the `Session -> Restart R` would as invoked from the menu.

**Comment by vnijs** [comment]
Thanks @kevinushey! Question: Is it possible to have R(studio) run a user provided command after restart? Like `rstudioapi::restartSession(cmd)`

**Comment by kevinushey** [comment]
Unfortunately no, not via that interface.

**Comment by vnijs** [comment]
@kevinushey Should create a new feature request for the combined functionality of `rstudioapi::executeCommand("restartR")` and `rstudioapi::restartSession(cmd)`?

**Comment by kevinushey** [comment]
I think we just need some way to configure `restartSession()` to behave like the "regular" restart session command.

**Comment by vnijs** [comment]
If `restartSession` could have the option (or default) to behave like `rstudioapi::executeCommand("restartR")` but with the option to run commands after running that would be fantastic!

**Comment by kevinushey** [comment]
I've filed https://github.com/rstudio/rstudio/issues/11378 for us to follow up this extension on the RStudio side.

**Comment by benfarmer05** [comment]
Hello, I am trying right now to run .rs.restartR() on an M1 Macbook 2020 (RStudio Version 2024.04.2+764 (2024.04.2+764)), and it does not properly clear variables or loaded packages. I have to run rstudioapi::executeCommand("restartR") to achieve that functionality. I am cross-posting this in https://github.com/rstudio/rstudio/pull/14230
